setwd("F:/")
library(Seurat)
library(dplyr)
library(ggplot2)
library("org.Mm.eg.db")
rt=read.table("symbol.txt",sep="\t",check.names=F,header=T)
genes=as.vector(rt[,1])
entrezIDs <- mget(genes, org.Mm.egSYMBOL2EG, ifnotfound=NA)
entrezIDs <- as.character(entrezIDs)
out=cbind(rt,entrezID=entrezIDs)
write.table(out,file="id.txt",sep="\t",quote=F,row.names=F)
library("clusterProfiler")
library("enrichplot")
library("ggplot2")
library(GOplot)
rt=read.table("id.txt",sep="\t",header=T,check.names=F)
rt=rt[is.na(rt[,"entrezID"])==F,]
gene=rt$entrezID
kk <- enrichGO(gene = gene, OrgDb = org.Mm.eg.db, pvalueCutoff =0.05, qvalueCutoff = 0.05, ont="BP", readable =T)
write.table(kk,file="GO.txt",sep="\t",quote=F,row.names = F)
pdf(file="barplot.pdf",width = 10,height = 8)
barplot(kk, drop = TRUE, showCategory =10,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
dev.off()
pdf(file="bubble.pdf",width = 10,height = 8)
dotplot(kk,showCategory = 10,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
dev.off()
ego=read.table("GO.txt", header = T,sep="\t",check.names=F)
go=data.frame(Category = "All",ID = ego$ID,Term = ego$Description, Genes = gsub("/", ", ", ego$geneID), adj_pval = ego$p.adjust)
id.fc <- read.table("id.txt", header = T,sep="\t",check.names=F)
genelist <- data.frame(ID = id.fc$gene, logFC = id.fc$avg_log2FC)
row.names(genelist)=genelist[,1]
circ <- circle_dat(go, genelist)
GOBubble(circ, display = "single", labels = 5, table.legend = F)
reduced_circ <- reduce_overlap(circ, overlap = 0.75)
GOBubble(reduced_circ, labels = 5, table.legend = F)
GOCircle(circ, nsub = 10, label.size = 5, rad1 = 3, rad2 = 4, table.legend = F)